### ISSUE TITLE
Import fails in (some) spyder versions

### ISSUE THREAD

**Issue by mwcraig** [vpython/vpython-jupyter#19]
From the vpython email list (https://groups.google.com/forum/?hl=en#!topic/vpython-users/jFiOpafJnkI):

```python
 from vpython import*
  box()
```

> there is an error showed in console:

```
  KeyError: 'default/interpreter/dedicated'
```

> but it is fine when I use Jupyter Notebook to run it.
>
> How can I fix this?
>
> The console message:

```
runfile('D:/user/Desktop/WPy64-3740/settings/.spyder-py3/temp.py', wdir='D:/user/Desktop/WPy64-3740/settings/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-1-e68d4507caad>", line 1, in <module>
    runfile('D:/user/Desktop/WPy64-3740/settings/.spyder-py3/temp.py', wdir='D:/user/Desktop/WPy64-3740/settings/.spyder-py3')

  File "D:\user\Desktop\WPy64-3740\python-3.7.4.amd64\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\user\Desktop\WPy64-3740\python-3.7.4.amd64\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/user/Desktop/WPy64-3740/settings/.spyder-py3/temp.py", line 8, in <module>
    from vpython import*

  File "D:\user\Desktop\WPy64-3740\python-3.7.4.amd64\lib\site-packages\vpython\__init__.py", line 57, in <module>
    _warn_if_spyder_settings_wrong()

  File "D:\user\Desktop\WPy64-3740\python-3.7.4.amd64\lib\site-packages\vpython\_notebook_helpers.py", line 15, in _warn_if_spyder_settings_wrong
    if not _spyder_run_setting_is_correct():

  File "D:\user\Desktop\WPy64-3740\python-3.7.4.amd64\lib\site-packages\vpython\_notebook_helpers.py", line 11, in _spyder_run_setting_is_correct
    return CONF['run']['default/interpreter/dedicated']

  File "D:\user\Desktop\WPy64-3740\python-3.7.4.amd64\lib\configparser.py", line 1251, in __getitem__
    raise KeyError(key)

KeyError: 'default/interpreter/dedicated'
```

**Comment by mwcraig** [comment]
This happens when the user is starting from spyder's default settings, apparently. Then the config item `default/interpreter/dedicated` is not present at all (as opposed to having the value `False`). If the user has at some point chosen to run in a dedicated console then the config item is present.

This is likely a spyder bug, but not sure I'll have time to track it down.
